# Generated by Django 5.2.5 on 2025-08-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_price_is_current_alter_pricetype_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricetype',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('price_type', 'is_current'), name='unique_current_price_per_type'),
        ),
        migrations.AddConstraint(
            model_name='pricetype',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_price_type_name_per_category'),
        ),
    ]
